"""add the upvote column in the upvotes table

Revision ID: c3118ee393c4
Revises: cdd5a616517a
Create Date: 2021-06-17 20:37:44.268205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3118ee393c4'
down_revision = 'cdd5a616517a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('upvote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upvotes', 'upvote')
    # ### end Alembic commands ###
